### ISSUE TITLE
PluginException: `ActionUpdateThread.OLD_EDT`

### ISSUE THREAD

**Issue by dubreuia** [dubreuia/python-inlay-hints-plugin#13]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.dubreuia.pih.actions.PythonVariableTypeInformationHintAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.dubreuia.pih]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

**Comment by ewi2345** [comment]
Have same Error -- How severe is that problem ..? 
Because I really like these inlay hints !!!
